on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Build"
      - name: Test
        run: |
          echo "Test"
      - name: Deploy
        run: |
          echo "Deploy"
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: |
          echo "Check"
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit test
        run: |
          echo "Easy test addition step"
  custom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit test
        run: bash ./sample.sh
        
